# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  #- trigger: ":espanso"
  #  replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m-%d-%Y"

  # Dates
  - trigger: ":ymd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":bd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%F"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

# Custom Replacements

#:mdtag is used to quickly create a tag notation for Zettlekasten in code blocks.
  - trigger: ":mdtag"
<<<<<<< HEAD
    replace: "`#$|$`  "
=======
    replace: "`#$|$`"
>>>>>>> 1f96044f41806aa2ae7d8e2ed23acee50906183c

#:t is a short version of mdtag
  - trigger: ":t"
    replace: "`#$|$`"

#fun stuff
  - trigger: ":dance"
    replace: "`ᕕ(⌐■_■)ᕗ ♪♬`"

  - trigger: ":flip"
    replace: "`(╯°□°）╯︵ ┻━┻`"

  - trigger: ":nice"
    replace: "𝓷𝓲𝓬𝓮 ☜(ﾟヮﾟ☜)"

<<<<<<< HEAD
  - trigger: ":dwi"
    replace: "(⌐■_■)"

  - trigger: ":hg"
    replace: "ᕕ( ᐛ )ᕗ"

  - trigger: ":eh"
    replace: "‽"

  - trigger: ":loading"
    replace: "███▒▒▒▒▒▒▒"

  - trigger: ":lol"
    replace: "L(° O °L)"

  - trigger: ":nerd"
    replace: "(⌐⊙_⊙)"

  - trigger: ":nuke"
    replace: "☢"

  - trigger: ":smile"
    replace: "ツ"

  - trigger: ":smirk"
    replace: "¬‿¬"

  - trigger: ":this"
    replace: "( ͡° ͜ʖ ͡°)_/¯"

  - trigger: ":derp"
    replace: "☉ ‿ ⚆"

  - trigger: ":cloud"
    replace: "☁"

#new note template for your Zettlekasten
  - trigger: ":nn"
    replace: "# Title\n{{date}}\n## Tags\n\n## Links \n\n### ID\n{{id}}"
=======
#new note template for your Zettlekasten
  - trigger: ":nn"
    replace: "# Title\n{{date}}  \nContent goes here\n\n## Tags\n\n## Links \n\n### ID\n{{id}}"
>>>>>>> 1f96044f41806aa2ae7d8e2ed23acee50906183c
    vars:
      - name: date
        type: match
        params:
          trigger: ":date"
      - name: id
        type: match
        params:
          trigger: ":id"

#time in 0H:0M notation
  - trigger: ":now"
    replace: "{{time}}  "
    vars:
      - name: time
        type: date
        params:
          format: "%l:%M %p"

#id creates a timestamp for unique ids in notes like Zettlr - handy for other apps that don't include that functionality
  - trigger: ":id"
    replace: "{{time}}  "
    vars:
      - name: time
        type: date
        params:
          format: "%Y%m%d%H%M%S"

<<<<<<< HEAD
#cf creates a code fence - enclosed three `'s
=======
#cf creates a code fence - enclosed three `'s for Zettlr use
>>>>>>> 1f96044f41806aa2ae7d8e2ed23acee50906183c
  - trigger: ":cf"
    replace: "```\n$|$\n```"
